import { Color } from "@nativescript/core/color";
import { ImageAsset } from "@nativescript/core/image-asset";
import { ImageSource as ImageSourceDefinition } from "@nativescript/core/image-source";
import { Font } from "@nativescript/core/ui/styling/font";
import { isFileOrResourcePath } from "@nativescript/core/utils/utils";
export { isFileOrResourcePath };
export declare class ImageSource implements ImageSourceDefinition {
    ios: null;
    android: null;
    desktop: any;
    get height(): number;
    get width(): number;
    get rotationAngle(): number;
    set rotationAngle(_value: number);
    constructor(nativeSource?: any);
    static fromAsset(asset: ImageAsset): Promise<ImageSource>;
    static fromUrl(url: string): Promise<ImageSource>;
    static fromResourceSync(name: string): ImageSource;
    static fromResource(name: string): Promise<ImageSource>;
    static fromFileSync(path: string): ImageSource;
    static fromFile(path: string): Promise<ImageSource>;
    static fromFileOrResourceSync(path: string): ImageSource;
    static fromDataSync(data: any): ImageSource;
    static fromData(data: any): Promise<ImageSource>;
    static fromBase64Sync(source: string): ImageSource;
    static fromBase64(source: string): Promise<ImageSource>;
    static fromFontIconCodeSync(source: string, font: Font, color: Color): ImageSource | any;
    fromAsset(asset: ImageAsset): Promise<this>;
    loadFromResource(name: string): boolean;
    fromResource(name: string): Promise<boolean>;
    loadFromFile(path: string): boolean;
    fromFile(path: string): Promise<boolean>;
    loadFromData(data: any): boolean;
    fromData(data: any): Promise<boolean>;
    loadFromBase64(source: string): boolean;
    fromBase64(source: string): Promise<boolean>;
    loadFromFontIconCode(source: string, font: Font, color: Color): boolean;
    setNativeSource(source: any): void;
    saveToFile(path: string, format: "png" | "jpeg" | "jpg", quality?: number): boolean;
    toBase64String(format: "png" | "jpeg" | "jpg", quality?: number): string;
}
export declare function fromAsset(asset: ImageAsset): Promise<ImageSource>;
export declare function fromResource(name: string): ImageSource;
export declare function fromFile(path: string): ImageSource;
export declare function fromData(data: any): ImageSource;
export declare function fromFontIconCode(source: string, font: Font, color: Color): ImageSource;
export declare function fromBase64(source: string): ImageSource;
export declare function fromNativeSource(nativeSource: any): ImageSource;
export declare function fromFileOrResource(path: string): ImageSource;
