export declare function hasKey(key: string): boolean;
export declare function getBoolean(key: string, defaultValue?: boolean): boolean;
export declare function getString(key: string, defaultValue?: string): string;
export declare function getNumber(key: string, defaultValue?: number): number;
export declare function setBoolean(key: string, value: boolean): void;
export declare function setString(key: string, value: string): void;
export declare function setNumber(key: string, value: number): void;
export declare function remove(key: string): void;
export declare function clear(): void;
export declare function flush(): boolean;
export declare function getAllKeys(): Array<string>;
